authors:
  joshooaj:
    name: Josh Hendricks
    description: Senior Principal Support Engineer
    avatar: https://avatars.githubusercontent.com/u/7669972
  tarterman:
    name: Jared Tarter
    description: Senior Principal Engineer
    avatar: https://avatars.githubusercontent.com/u/42384254
