@{
    'Get-Log'                  = 'Get-VmsLog'
    'Get-HardwareDriver'       = 'Get-VmsHardwareDriver'
    'Get-LicenseInfo'          = 'Get-VmsLicenseInfo'
    'Get-LicenseDetails'       = 'Get-VmsLicenseDetails'
    'Get-LicensedProducts'     = 'Get-VmsLicensedProducts'
    'Get-LicenseOverview'      = 'Get-VmsLicenseOverview'
    'Invoke-LicenseActivation' = 'Invoke-VmsLicenseActivation'
    'Get-CameraSetting'        = 'Get-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Get-MicrophoneSetting'    = 'Get-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Get-SpeakerSetting'       = 'Get-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Get-MetadataSetting'      = 'Get-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Get-InputSetting'         = 'Get-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Get-OutputSetting'        = 'Get-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Set-CameraSetting'        = 'Set-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Set-MicrophoneSetting'    = 'Set-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Set-SpeakerSetting'       = 'Set-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Set-MetadataSetting'      = 'Set-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Set-InputSetting'         = 'Set-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
    'Set-OutputSetting'        = 'Set-VmsDeviceGeneralSetting and Get-VmsDeviceStreamSetting'
}
